"""Command-line entry point for AI Study Assistant.

Exposed as the ``rulebook`` console script:

- ``rulebook serve``   start the backend (and the bundled web UI)
- ``rulebook init``    create .env and the working directories
- ``rulebook check``   verify the environment and dependencies
- ``rulebook analytics`` aggregate AI vs expert sign-off (overturn / edit rates)
- ``rulebook --version``
"""

from __future__ import annotations

import argparse
import importlib.util
import shutil
import sys
from pathlib import Path

from backend import __version__

CORE_DEPENDENCIES = {
    "fastapi": "fastapi",
    "uvicorn": "uvicorn",
    "dotenv": "python-dotenv",
    "sentence_transformers": "sentence-transformers",
    "sklearn": "scikit-learn",
    "pypdf": "pypdf",
    "multipart": "python-multipart",
    "faiss": "faiss-cpu",
    "langgraph": "langgraph",
    "sqlalchemy": "SQLAlchemy",
    "psycopg": "psycopg[binary]",
    "docx": "python-docx",
    "openpyxl": "openpyxl",
}

# Minimal working configuration for `init` when no full .env.example is available
# (pip-installed usage). The source repository ships the complete .env.example.
MINIMAL_ENV_TEMPLATE = """\
# Rulebook configuration (generated by `rulebook init`).
# See https://github.com/ZQR1101/rulebook for the full option list.

# Any OpenAI-compatible chat provider works. DeepSeek example:
DEEPSEEK_API_KEY=your_api_key_here
DEEPSEEK_BASE_URL=https://api.deepseek.com
DEEPSEEK_MODEL=deepseek-v4-pro

# Set a real key above; offline tests work without one, LLM calls need it.
ENABLE_LLM_JUDGE=true

# Local RAG (FAISS + sentence-transformers). The embedding model downloads
# from Hugging Face on first use unless EMBEDDING_MODEL_PATH points at a local copy.
EMBEDDING_MODEL_LOCAL_ONLY=false
ENABLE_RAG_AUTO_BUILD=true

# Three-layer learning memory and optional reranker.
ENABLE_MEMORY=false
ENABLE_RERANKER=false
QUERY_REWRITE_MODE=off

# Human-in-the-loop tool approval keys (must differ, >=32 chars each).
ENABLE_INSECURE_DEV_TOOL_KEYS=false
TOOL_APPROVAL_KEY=replace-with-a-long-random-requester-secret
TOOL_APPROVER_KEY=replace-with-a-different-long-random-approver-secret
"""

WORKING_DIRS = ("docs", "rag_index", "data", "logs")


def _print_result(status: str, message: str) -> None:
    print(f"[{status}] {message}")


def _resolve_project_root() -> Path:
    from backend.config import PROJECT_ROOT

    return PROJECT_ROOT


def cmd_serve(args: argparse.Namespace) -> int:
    import uvicorn

    root = _resolve_project_root()
    _print_result("INFO", f"Project root: {root}")
    _print_result(
        "INFO",
        f"Starting AI Study Assistant on http://{args.host}:{args.port} "
        "(API docs at /docs)...",
    )
    uvicorn.run(
        "backend.server:app",
        host=args.host,
        port=args.port,
        reload=args.reload,
    )
    return 0


def _find_env_example() -> Path | None:
    candidates = [
        _resolve_project_root() / ".env.example",
        Path(__file__).parent / "env.example",
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return None


def cmd_init(args: argparse.Namespace) -> int:
    root = _resolve_project_root()
    env_file = root / ".env"

    if env_file.exists() and not args.force:
        _print_result("SKIP", f".env already exists: {env_file}")
    else:
        env_example = _find_env_example()
        if env_example is not None:
            shutil.copyfile(env_example, env_file)
            _print_result("OK", f"Created .env from {env_example.name}: {env_file}")
        else:
            env_file.write_text(MINIMAL_ENV_TEMPLATE, encoding="utf-8")
            _print_result("OK", f"Created .env with a minimal template: {env_file}")
        _print_result("HINT", "Edit .env and set a real model API key before chatting.")

    for name in WORKING_DIRS:
        target = root / name
        if target.exists():
            _print_result("SKIP", f"{name}/ already exists")
        else:
            target.mkdir(parents=True, exist_ok=True)
            _print_result("OK", f"Created {name}/")

    static_dir = Path(__file__).parent / "static"
    if static_dir.is_dir():
        _print_result("OK", f"Web UI bundled at {static_dir}")
    else:
        _print_result(
            "INFO",
            "Web UI static files are not bundled (development checkout). "
            "Run `npm install && npm run build`, or use `npm run dev` while developing.",
        )

    _print_result("OK", "Init complete. Start the app with: rulebook serve")
    return 0


def cmd_check(_args: argparse.Namespace) -> int:
    ok = True

    version = sys.version_info
    python_ok = version >= (3, 11)
    _print_result(
        "OK" if python_ok else "ERROR",
        f"Python {version.major}.{version.minor}.{version.micro}",
    )
    ok &= python_ok

    missing = [
        package
        for module, package in CORE_DEPENDENCIES.items()
        if importlib.util.find_spec(module) is None
    ]
    if missing:
        _print_result("ERROR", f"Missing dependencies: {', '.join(missing)}")
        _print_result("HINT", "Run: pip install rulebook-review")
        ok = False
    else:
        _print_result("OK", "All core dependencies are importable")

    try:
        from backend.config import get_config

        config = get_config()
        _print_result("OK", f"Config loaded; model={config.model}")
        _print_result("INFO", f"Project root: {config.project_root}")
        _print_result("INFO", f"Docs dir: {config.docs_path}")
        _print_result("INFO", f"RAG index dir: {config.rag_index_dir}")
        if config.has_api_key:
            _print_result("OK", f"Model API key configured via {config.api_key_source}")
        else:
            _print_result("WARN", "No model API key; offline features work, LLM calls fail")
    except Exception as error:  # noqa: BLE001 - report any config failure
        _print_result("ERROR", f"Cannot load backend.config: {error}")
        return 1

    try:
        import backend.server  # noqa: F401

        _print_result("OK", "backend.server imports cleanly")
    except Exception as error:  # noqa: BLE001
        _print_result("ERROR", f"Cannot import backend.server: {error}")
        ok = False

    root = _resolve_project_root()
    index_file = root / "rag_index" / "index.faiss"
    if index_file.exists():
        _print_result("OK", "RAG index present")
    else:
        _print_result(
            "WARN",
            "RAG index not built yet; it is created automatically on first vector search "
            "(or POST /rebuild-index)",
        )

    if Path(__file__).parent.joinpath("static").is_dir():
        _print_result("OK", "Web UI static files bundled")
    else:
        _print_result("INFO", "Web UI static files not bundled; API-only mode")

    _print_result("OK" if ok else "ERROR", "Check finished")
    return 0 if ok else 1


def _ensure_platform_schema() -> None:
    """Idempotent table creation / additive columns — only ``serve`` runs it at startup."""

    from backend.platform_db import init_platform_db

    init_platform_db()


def cmd_review(args: argparse.Namespace) -> int:
    """Headless single-document review: upload → engine → scorecard printout."""

    from backend.documents.models import Document
    from backend.documents.service import create_document
    from backend.engine.orchestrator import ReviewConflict, run_review
    from backend.platform_db import platform_session

    _ensure_platform_schema()

    source = Path(args.file).expanduser().resolve()
    if not source.is_file():
        _print_result("ERROR", f"File not found: {source}")
        return 1

    session = platform_session()
    try:
        document, created = create_document(
            session,
            playbook_id=args.playbook,
            filename=source.name,
            content=source.read_bytes(),
            actor="cli",
        )
        if not created:
            _print_result("SKIP", f"Duplicate content — already reviewed as {document.friendly_id}")
            return 0
        document_id = document.id
        friendly = document.friendly_id
    finally:
        session.close()

    _print_result("INFO", f"Ingested as {friendly}; running review engine...")
    try:
        engine_run = run_review(document_id, trigger="cli")
    except ReviewConflict as exc:
        _print_result("ERROR", str(exc))
        return 1
    except Exception as exc:  # noqa: BLE001
        _print_result("ERROR", f"Review failed: {exc}")
        return 1

    _print_result(
        "OK",
        f"Review finished in {engine_run.total_latency_ms} ms "
        f"({engine_run.status})",
    )
    session = platform_session()
    try:
        document = session.get(Document, document_id)
        scorecard = document.scorecard or {}
        counts = scorecard.get("counts", {})
        print()
        print(f"=== {friendly} · {document.title} ===")
        print(
            f"红 {counts.get('red', 0)} | 黄 {counts.get('amber', 0)} | 绿 {counts.get('green', 0)}"
            f"    风险指数 {scorecard.get('risk_index', 0)}/100"
            f"    覆盖率 {scorecard.get('coverage_pct', 0)}%"
        )
        for verdict in document.verdicts:
            rule = verdict.rule
            label = {"red": "红", "amber": "黄", "green": "绿"}.get(verdict.rating, "?")
            line = f"[{label}] {rule.name}（{rule.dimension}）: {verdict.rationale[:80]}"
            print(line)
            if verdict.gap_reason:
                print(f"      缺口: {verdict.gap_reason}")
    finally:
        session.close()
    print()
    _print_result("HINT", "Open the web UI to review, sign off, and export deliverables.")
    return 0


def cmd_analytics(args: argparse.Namespace) -> int:
    """Sign-off analytics: how much of the AI's first pass the experts kept."""

    import json

    from backend.analytics import build_report, render_markdown
    from backend.platform_db import platform_session

    _ensure_platform_schema()
    session = platform_session()
    try:
        report = build_report(session)
    finally:
        session.close()

    if not report["overall"]["decided"]:
        _print_result(
            "WARN",
            "平台库中还没有专家签字记录，改判率无从计算。"
            "先在 Web UI 完成签字，或用 PATCH /documents/{document_id}/verdicts/{verdict_id}。",
        )
    payload = (
        json.dumps(report, ensure_ascii=False, indent=2)
        if args.json
        else render_markdown(report)
    )
    if args.output:
        path = Path(args.output).expanduser().resolve()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(payload + "\n", encoding="utf-8")
        _print_result("OK", f"分析报告已写入 {path}")
    else:
        print(payload)
    return 0


def cmd_inbox(args: argparse.Namespace) -> int:
    """Run the watched-folder auto-intake loop."""

    from backend.engine.inbox_watcher import inbox_dir, run_watcher

    _print_result("INFO", f"Watching {inbox_dir()} (playbook: {args.playbook})")
    _print_result("INFO", "Drop supported documents into the folder; Ctrl+C stops.")
    try:
        stats = run_watcher(
            playbook_id=args.playbook,
            interval_seconds=args.interval,
            settle_interval=args.settle,
            once=args.once,
        )
    except KeyboardInterrupt:
        _print_result("OK", "Watcher stopped")
        return 0
    _print_result(
        "OK",
        f"Ingested {stats.ingested}, duplicates {stats.duplicates}, "
        f"dead-lettered {stats.dead_lettered}",
    )
    return 0


def cmd_mail(args: argparse.Namespace) -> int:
    """Run the IMAP mail intake loop (requires MAIL_* configuration)."""

    from backend.engine.mail_inbox import run_mail_loop

    _print_result("INFO", f"Mail intake loop starting (default playbook: {args.playbook})")
    _print_result("INFO", "Configure MAIL_HOST/MAIL_USER/MAIL_PASSWORD in .env; Ctrl+C stops.")
    try:
        stats = run_mail_loop(
            default_playbook=args.playbook,
            interval_seconds=args.interval,
            once=args.once,
        )
    except KeyboardInterrupt:
        _print_result("OK", "Mail loop stopped")
        return 0
    _print_result(
        "OK",
        f"Reviewed {stats['reviewed']}, duplicates {stats['duplicates']}, "
        f"skipped {stats['skipped']}, failed {stats['failed']}",
    )
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="rulebook",
        description="AI Study Assistant: local web app + CLI for study-focused RAG, agents and memory.",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")

    subparsers = parser.add_subparsers(dest="command", required=True)

    serve = subparsers.add_parser("serve", help="Start the backend and bundled web UI")
    serve.add_argument("--host", default="127.0.0.1", help="Bind address (default: 127.0.0.1)")
    serve.add_argument("--port", type=int, default=8000, help="Port (default: 8000)")
    serve.add_argument("--reload", action="store_true", help="Enable auto-reload (development)")
    serve.set_defaults(func=cmd_serve)

    init = subparsers.add_parser("init", help="Create .env and working directories")
    init.add_argument("--force", action="store_true", help="Overwrite an existing .env")
    init.set_defaults(func=cmd_init)

    check = subparsers.add_parser("check", help="Verify environment and dependencies")
    check.set_defaults(func=cmd_check)

    from backend.playbooks import list_playbook_ids

    playbook_help = f"Playbook id: {', '.join(list_playbook_ids())}"

    review = subparsers.add_parser("review", help="Review one document and print the scorecard")
    review.add_argument("file", help="Path to the document (.pdf/.docx/.md/.txt)")
    review.add_argument("--playbook", default="contract-compliance", help=playbook_help)
    review.set_defaults(func=cmd_review)

    analytics = subparsers.add_parser(
        "analytics",
        help="Aggregate AI first-pass vs expert sign-off: overturn and edit rates",
    )
    analytics.add_argument("--json", action="store_true", help="输出 JSON 而非 Markdown")
    analytics.add_argument("--output", help="写入文件路径（默认打印到终端）")
    analytics.set_defaults(func=cmd_analytics)

    inbox = subparsers.add_parser("inbox", help="Run the watched-folder auto-intake loop")
    inbox.add_argument("--playbook", default="contract-compliance", help=playbook_help)
    inbox.add_argument("--interval", type=float, default=10.0, help="Poll interval seconds")
    inbox.add_argument("--settle", type=float, default=2.0, help="File-settle window seconds")
    inbox.add_argument("--once", action="store_true", help="Single poll pass and exit")
    inbox.set_defaults(func=cmd_inbox)

    mail = subparsers.add_parser("mail", help="Run the IMAP mail intake loop")
    mail.add_argument("--playbook", default="contract-compliance", help=playbook_help)
    mail.add_argument("--interval", type=float, default=60.0, help="Poll interval seconds")
    mail.add_argument("--once", action="store_true", help="Single poll pass and exit")
    mail.set_defaults(func=cmd_mail)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
